server:
  port: 8082
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

jwt:
  signerKey: "akdXchw5FloESb63Kc+DFhTARvpkowiUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
  valid-duration: 1 #in day
  refreshable-duration: 3 #inday
