server:
  port: 8888
app:
  api-prefix: /api/v3
spring:
  cloud:
    gateway:
      default-filters:
        - RequestSize=2000000
      routes:
        - id: identity-service
          uri: http://localhost:8082
          predicates:
            - Path=${app.api-prefix}/identity/**
          filters:
            - StripPrefix=2
        - id: profile-service
          uri: http://localhost:8081
          predicates:
            - Path=${app.api-prefix}/profile/**
          filters:
            - StripPrefix=2
        - id: notification-service
          uri: http://localhost:8083
          predicates:
            - Path=${app.api-prefix}/notification/**
          filters:
            - StripPrefix=2
        - id: file-service
          uri: http://localhost:8084
          predicates:
            - Path=${app.api-prefix}/file/**
          filters:
            - StripPrefix=2
        - id: post-service
          uri: http://localhost:8085
          predicates:
            - Path=${app.api-prefix}/post/**
          filters:
            - StripPrefix=2
        - id: websocket
          uri: http://localhost:8088
          predicates:
            - Path=${app.api-prefix}/websocket/**
          filters:
            - StripPrefix=2
        - id: location-service
          uri: http://localhost:8086
          predicates:
            - Path=${app.api-prefix}/location/**
          filters:
            - StripPrefix=2
        - id: payment-service
          uri: http://localhost:8087
          predicates:
            - Path=${app.api-prefix}/payment/**
          filters:
            - StripPrefix=2