server:
  port: 8082
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
  datasource:
    url: "jdbc:mysql://localhost:3306/identity"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  kafka:
    bootstrap-servers: "${kafka:localhost}:9094"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    redis:
      host: "${redis:localhost}"
      port: 6380

application:
  config:
    profile-url: http://localhost:8081/profile
    jwt:
      signerKey: "akdXchw5FloESb63Kc+DFhTARvpkowiUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"
      valid-duration: 1 #in day
      refreshable-duration: 3 #inday
