spring:
  datasource:
    url: "jdbc:mysql://${mysqldb:localhost}:3306/location"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: none
  #    database: postgresql
  #    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: "${kafka:localhost}:9094"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: ws-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: "${redis:localhost}"
      port: 6380

application:
  config:
    post-url: http://localhost:8085/post
    identity-url: http://localhost:8082/identity

server:
  port: 8086
  servlet:
    context-path: /location