spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/location
    username: admin
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8086
  servlet:
    context-path: /location