spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/location
    username: admin
    password: Admin@123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: "${kafka:localhost}:9094"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: websocket-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
  data:
    redis:
      host: "${redis:localhost}"
      port: 6380
application:
  config:
    post-url: http://localhost:8085/post
    identity-url: http://localhost:8082/identity
server:
  port: 8086
  servlet:
    context-path: /location