server:
  port: 8083
  servlet:
    context-path: /notification

spring:
  data:
    mongodb:
      username: root
      password: root
      host: ${mongodb:localhost}
      port: 27017
      database: notification
      authentication-database: admin
  kafka:
    bootstrap-servers: "${kafka:localhost}:9094"
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

notification:
  email:
    brevo-url: https://api.brevo.com
    brevo-apikey: <your-key>