server:
  port: 8087
  servlet:
    context-path: /payment

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/payment"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true