server:
  port: 8087
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service
  datasource:
    url: "jdbc:mysql://localhost:3306/payment"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

application:
  config:
    post-url: http://localhost:8085/post
  payment:
    vnPay:
      url: "https://sandbox.vnpayment.vn/paymentv2/vpcpay.html"
      tmnCode: "ZDDQNEDU"
      secretKey: "FAONAXJYWAKCGIDJDSKFGHIWDRCJQAET"
      returnUrl: "http://${backend:localhost}}:8888/api/v3/payment/payments/vn-pay-callback"
      version: "2.1.0"
      command: "pay"
      orderType: "other"