spring:
  application:
    name: post-service
  datasource:
    url: "jdbc:mysql://${mysqldb:localhost}:3306/post"
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  kafka:
    bootstrap-servers: "${kafka:localhost}:9094"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

application:
  config:
    file-url: http://localhost:8084/file
    location-url: http://localhost:8086/location
    payment-url: http://localhost:8087/payment
    profile-url: http://localhost:8081/profile

server:
  port: 8085
  servlet:
    context-path: /post