server:
  port: 8081
  servlet:
    context-path: /profile
spring:
  application:
    name: profile-service
  datasource:
    url: "jdbc:mysql://localhost:3306/profile"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: root
    password: Admin@123
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

    